name: CI

on:
  pull_request:
    branches-ignore: [main]

jobs:
  swift:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cd macos && swift build

      - name: Test
        run: cd macos && swift test
